#---------------------------------------------------------------
# Project         : Mandriva Linux
# Module          : dynamic
# File            : Makefile
# Version         : $Id: Makefile 254719 2009-03-25 15:55:53Z fcrozat $
# Author          : Frederic Lepied
# Created On      : Wed Mar  7 07:36:50 2001
#---------------------------------------------------------------

PACKAGE = dynamic
VERSION = 0.26.17

SVNROOT = svn+ssh://svn.mandriva.com/svn/soft/$(PACKAGE)

sysconfdir = /etc
topdir = $(sysconfdir)/dynamic
datadir = /usr/share
commondir = $(datadir)/dynamic

INSTALL = /usr/bin/install -c

LAUNCHER_DIRS = launchers/*
FILES = AUTHORS Makefile ChangeLog dynamic-devfsd scripts/*.script user-scripts/*.script \
        hooks/*.hook $(LAUNCHER_DIRS) dynamic-udev.rules

all:
	@echo $(VERSION)

clean:
	rm -f *~ scripts/*~ hooks/*~ launchers/*/*~

install:
	mkdir -p $(topdir)/{scripts,hooks,launchers,user-scripts}
	$(INSTALL) -m 755 scripts/*.script $(topdir)/scripts/
	$(INSTALL) -m 755 user-scripts/*.script $(topdir)/user-scripts/
	rm -f $(topdir)/user-scripts/functions.script
	mkdir -p $(commondir)
	install -m 644 user-scripts/functions.script $(commondir)
	$(INSTALL) -m 755 hooks/*.hook $(topdir)/hooks/
	mkdir -p $(sysconfdir)/udev/rules.d/
	$(INSTALL) -m 644 dynamic-udev.rules $(sysconfdir)/udev/rules.d/60-dynamic.rules
	for i in $(LAUNCHER_DIRS) ; do \
		mkdir -p $(topdir)/$$i ; \
		$(INSTALL) -m 755 $$i/*.desktop $(topdir)/$$i ; \
	done

localdist: cleandist dir localcopy tar

cleandist:
	rm -rf $(PACKAGE)-$(VERSION) $(PACKAGE)-$(VERSION).tar.bz2

dir:
	mkdir $(PACKAGE)-$(VERSION)

localcopy:
	tar c $(FILES) | tar x -C $(PACKAGE)-$(VERSION)

tar:
	tar cvf $(PACKAGE)-$(VERSION).tar $(PACKAGE)-$(VERSION)
	bzip2 -9vf $(PACKAGE)-$(VERSION).tar
	rm -rf $(PACKAGE)-$(VERSION)


release: changelog svntag dist

dist: cleandist export tar

export:
	svn export $(SVNROOT)/tags/$(VERSION) $(PACKAGE)-$(VERSION)

svntag:
	svn copy $(SVNROOT)/trunk $(SVNROOT)/tags/$(VERSION) -m $(VERSION)

changelog: ../common/username
#svn2cl is available in our contrib.
	svn2cl --authors ../common/username.xml --accum
	rm -f ChangeLog.bak
	svn commit -m "Generated by svn2cl the `date '+%c'`" ChangeLog

# Local variables:
# mode: makefile
# End:
#
# Makefile.in ends here
